# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.0
  - hhvm

services:
- mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_testing;'

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  # - mysql -e 'create database db_testing;'
# before_script:
#   - cp .env.travis .env
# - mysql -e 'create database db_testing;'
# - composer self-update
# - composer install --no-interaction
# - php artisan key:generate
# - php artisan migrate --seed



Commands you want to run that will verify your build.
script: vendor/phpunit/phpunit

# # after_script:
#   - wget https://scrutinizer-ci.com/ocular.phar
#   - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: '5.6'
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
